export const Roles = {
    OWNER: "OWNER",
    ADMIN: "ADMIN",
    MEMBER: "MEMBER",
} as const;

export const Permissions = {
    CREATE_ORGANIZATION: "CREATE_ORGANIZATION",
    DELETE_ORGANIZATION: "DELETE_ORGANIZATION",
    EDIT_ORGANIZATION: "EDIT_ORGANIZATION",
    MANAGE_ORGANIZATION_SETTINGS: "MANAGE_ORGANIZATION_SETTINGS",

    ADD_MEMBER: "ADD_MEMBER",
    CHANGE_MEMBER_ROLE: "CHANGE_MEMBER_ROLE",
    REMOVE_MEMBER: "REMOVE_MEMBER",

    CREATE_PROGRAM: "CREATE_PROGRAM",
    EDIT_PROGRAM: "EDIT_PROGRAM",
    DELETE_PROGRAM: "DELETE_PROGRAM",
    VIEW_PROGRAM: "VIEW_PROGRAM",

    CREATE_EVENT: "CREATE_EVENT",
    EDIT_EVENT: "EDIT_EVENT",
    DELETE_EVENT: "DELETE_EVENT",

    VIEW_ONLY: "VIEW_ONLY",
} as const;

export type RoleType = keyof typeof Roles;

export type PermissionType = keyof typeof Permissions;
